version: "3"

services:
  db:
    build:
      context: ./db
    env_file: .env
    volumes:
      - ./db/.dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  server:
    depends_on:
      - db
      - mosquitto
    env_file: .env
    build:
      context: ./server
    ports:
      - "${USERSERVICE_PORT}:80"

  mosquitto:
    build:
      context: ./mosquitto
    env_file: .env
    ports:
      - "${BROKER_PORT}:1884"

  subscriber:
    env_file: .env
    depends_on:
      - db
      - mosquitto
    build:
      context: ./subscriber
