version: "3"

services:
  db:
    build:
      context: ./db
    env_file: .env
    volumes:
      - ./db/.dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  http_server:
    depends_on:
      - db
    build:
      context: ./http_server
    ports:
      - 80:80

  mosquitto:
    build:
      context: ./mosquitto
    env_file: .env
    ports:
      - 1884:1883

  mqtt:
    depends_on:
      - db
      - mosquitto
    env_file: .env
    build:
      context: ./mqtt
